
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;                       // Import essential packages
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTextField;
import javax.swing.Timer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 * 
 */

 
 
public class supplier extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement pst;              // declare three variables for using database connecting
    ResultSet rs;
    
   

    /**
     * Creates new form supplier
     */
    public supplier() {
        initComponents();               //called the created classes in supplier frame
        autoIncrement();
        dateshowing();
        timeshowing();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
 
    @SuppressWarnings("unchecked")
       
    public void autoIncrement()                                    // create the class for increment, public means that the method is visible and can be called from other objects of other types
    {
       
            try {
                Class.forName("com.mysql.jdbc.Driver");
                
                con=(com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/baby_shop","root","");   // establish a connection with a database
                Statement s=con.createStatement();
                
                rs=s.executeQuery("select Max(sup_code) from supplier ");  // send SQL statements
                rs.next();  //  it shifts the cursor to the next row of the result set from the database and returns true if there is any row, otherwise false
                rs.getString("Max(sup_code)"); // get the maximum value of the sup_code
                
                if(rs.getString("Max(sup_code)")==null)  // if maximum value is null
                    
                {
                     s_code.setText("D0001");  // set the value to s_code
                }
                else{                          //if maximum value is not null
                    
                    Long sup_code=Long.parseLong(rs.getString("Max(sup_code)").substring(2,(rs.getString("Max(sup_code)").length()))); // substring a string to(2,length(sup_code)) & get the maximum value of it
                    sup_code++;     //increment the value of maximum value of above substring variable
                    s_code.setText("D0" +String.format("%03d",sup_code)); // enter the value to s_code , sup_code value get as three place value and add with "D0"
  
                }      
           
          }catch (ClassNotFoundException | SQLException ex) {  //handle the sql errors
                Logger.getLogger(supplier.class.getName()).log(Level.SEVERE, null, ex);
            }
            
    
}
    public void dateshowing(){
         Date da = new Date();
         DateFormat si = new SimpleDateFormat("yyyy-MM-dd");
         datelbl.setText(si.format(da));
     }
     public void timeshowing(){
          new Timer(0,new ActionListener(){

              @Override
              public void actionPerformed(ActionEvent e) {
                   Date da = new Date();
                    DateFormat si = new SimpleDateFormat("hh:mm:ss a");
                    timelbl.setText(si.format(da));
              }
              
          }
                  
          ).start();
     }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        s_code = new javax.swing.JTextField();
        s_name = new javax.swing.JTextField();
        s_address = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        ips = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        insert = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        voudetailbtn = new javax.swing.JButton();
        voutablebtn = new javax.swing.JButton();
        printdatabtn = new javax.swing.JButton();
        suptablebtn = new javax.swing.JButton();
        timelbl = new javax.swing.JLabel();
        datelbl = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();

        label1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 800));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel7.setBackground(new java.awt.Color(255, 255, 204));
        jLabel7.setFont(new java.awt.Font("Century", 1, 48)); // NOI18N
        jLabel7.setText("Supplier Details");

        s_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_codeActionPerformed(evt);
            }
        });

        ips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipsActionPerformed(evt);
            }
        });

        l1.setBackground(new java.awt.Color(255, 204, 204));
        l1.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        l1.setText("Supplier Code");

        l2.setBackground(new java.awt.Color(255, 204, 204));
        l2.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        l2.setText("Supplier Name");

        l3.setBackground(new java.awt.Color(255, 204, 204));
        l3.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        l3.setText("Address");

        l4.setBackground(new java.awt.Color(255, 204, 204));
        l4.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        l4.setText("Contact Number");

        l5.setBackground(new java.awt.Color(255, 204, 204));
        l5.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        l5.setText("Gmail");

        l6.setBackground(new java.awt.Color(255, 204, 204));
        l6.setFont(new java.awt.Font("Sitka Small", 1, 16)); // NOI18N
        l6.setText("Initial Products Supply");

        insert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        insert.setText("INSERT");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(s_name, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addComponent(s_code)
                    .addComponent(s_address)
                    .addComponent(contact)
                    .addComponent(mail)
                    .addComponent(ips))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_code, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_address, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ips, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("CATEGORY");

        voudetailbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        voudetailbtn.setText("VOUCHER DETAIL");
        voudetailbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voudetailbtnActionPerformed(evt);
            }
        });

        voutablebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        voutablebtn.setText("VOUCHER TABLE");
        voutablebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voutablebtnActionPerformed(evt);
            }
        });

        printdatabtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        printdatabtn.setText("PRINT DATA");
        printdatabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printdatabtnActionPerformed(evt);
            }
        });

        suptablebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        suptablebtn.setText("SUPPLIER TABLE");
        suptablebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suptablebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(printdatabtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(voutablebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(voudetailbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(suptablebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addComponent(suptablebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(voudetailbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(voutablebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(printdatabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        timelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        timelbl.setText("jLabel9");

        datelbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        datelbl.setText("jLabel9");

        label2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(timelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        String name,address,contact1,mail1,ips1=null;   // difine the variables as string
        name=s_name.getText();
        address=s_address.getText();
        contact1=contact.getText();                    // get the values from frame to above define variables
        mail1=mail.getText();
        ips1=ips.getText();
        
        if(name.isEmpty()) {
           label2.setText("Please enter the supplier name.");     // if name text is empty , give the msg as label
           return ;
        
        }else if (address.isEmpty()) {
           label2.setText("Please enter the supplier address."); // if address text is empty , give the msg as label
           return;
        }else if (contact1.isEmpty()) {
           label2.setText("Please enter the supplier contact number."); // if contact text is empty , give the msg as label
           return;
        }else if (mail1.isEmpty()) {
           label2.setText("Please enter the supplier gmail."); // if gmail text is empty , give the msg as label
           return;
        }else if (ips1.isEmpty()) {
           label2.setText("Please enter the description."); // if discription text is empty , give the msg as label
           return;
        }
        label2.setText("Detail enter Successful.");   //give  a msg for successfull data entry.
        
        
        try{
            String sql = "INSERT INTO supplier"
                    +"(sup_code, sup_name, sup_address, sup_contact, sup_gmail, description)"   // define a string variable and give the sql statement for insert
                    +" VALUES (?,?,?,?,?,?)";
            con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/baby_shop","root","");  //establish a connection with a database
            pst = (com.mysql.jdbc.PreparedStatement) con.clientPrepareStatement(sql);
            pst.setString(1,s_code.getText());
            pst.setString(2,s_name.getText());
            pst.setString(3,s_address.getText());     // set the values to database given from the text in frame
            pst.setString(4,contact.getText());
            pst.setString(5,mail.getText());
            pst.setString(6,ips.getText());
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Inserted Successfully");   // give a msgbox for successful data inserting.
            this.setVisible(false);                                        //close this frame
            sup_table spt =new sup_table();
            spt.setVisible(true);                                          //open new frame named as sup_table
            
            
       }
       catch(SQLException | HeadlessException ex){                         // handle the sql errors
           JOptionPane.showMessageDialog(null,ex);
       }
    }//GEN-LAST:event_insertActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed

        s_name.setText(null);
        s_address.setText(null);
        contact.setText(null);                                           // set the null values for given text boxes.
        mail.setText(null);
        ips.setText(null);
        label2.setText(null);
    }//GEN-LAST:event_resetActionPerformed

    private void s_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_codeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_s_codeActionPerformed

    private void ipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipsActionPerformed

    private void suptablebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suptablebtnActionPerformed
       sup_table st = new sup_table();
       st.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_suptablebtnActionPerformed

    private void voudetailbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voudetailbtnActionPerformed
       Payment_Voucher pv = new Payment_Voucher();
       pv.setVisible(true);
       this.setVisible(false); 
    }//GEN-LAST:event_voudetailbtnActionPerformed

    private void voutablebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voutablebtnActionPerformed
       vou_table vt = new vou_table();
       vt.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_voutablebtnActionPerformed

    private void printdatabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printdatabtnActionPerformed
        printframe pf = new printframe();
       pf.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_printdatabtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supplier().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contact;
    public static javax.swing.JLabel datelbl;
    private javax.swing.JButton insert;
    private javax.swing.JTextField ips;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JTextField mail;
    private javax.swing.JButton printdatabtn;
    private javax.swing.JButton reset;
    private javax.swing.JTextField s_address;
    public static javax.swing.JTextField s_code;
    private javax.swing.JTextField s_name;
    private javax.swing.JButton suptablebtn;
    public static javax.swing.JLabel timelbl;
    private javax.swing.JButton voudetailbtn;
    private javax.swing.JButton voutablebtn;
    // End of variables declaration//GEN-END:variables
}
